### PR TITLE
Switch to ps2homebrew docker image

### PR DESCRIPTION
**Pull request by AKuHAK**

### CODE REVIEW

**Comment by AKuHAK** [comment]
Source code for Docker image is here:
https://github.com/ps2homebrew/ps2homebrew/blob/main/Dockerfile

**Comment by AKuHAK** [comment]
benefits of using this image:
- no need for installing packages each action time
- ghcr.io is integrated into github, thus faster download speed and less bandwidth

**Comment by rickgaiser** [comment]
Is this image always up-to-date with ps2dev docker images?

**Comment by AKuHAK** [comment]
> Is this image always up-to-date with ps2dev docker images?

Yes, it is updated once [dispatch action](https://github.com/organizations/ps2homebrew/settings/secrets/actions) received from the https://github.com/ps2dev/ps2dev/blob/master/.github/workflows/docker.yml#L70
So it will be updated at the same time when current Docker image is updated (maybe a bit later cause it will need more time to install packages).

**Comment by AKuHAK** [comment]
https://github.com/ps2homebrew/ps2dev_forwarder/blob/master/.github/workflows/dispatcher.yml

**Comment by rickgaiser** [comment]
Alright, lets try it :).

**Pull request merged**
